CONTIKI_PROJECT = specksense
all: $(CONTIKI_PROJECT)
PROJECT_SOURCEFILES += kmeans.c
CONTIKI = ../contiki-2.7
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
include $(CONTIKI)/Makefile.include
CFLAGS+=-I$(CONTIKI)
CFLAGS+=-DPROCESS_ID=2
CFLAGS+=-DRUN_LENGTH=400
CFLAGS+=-DNUM_RECORDS=1
CFLAGS+=-DWITH_BOOST_CPU
CFLAGS+=-DRADIO_CHANNEL=15
CFLAGS+=-DPOWER_LEVELS=4
CFLAGS+=-DTIME_WINDOW=1000
CFLAGS+=-DDEBUG_RSSI=1
CFLAGS+=-DCHANNEL_METRIC=2

CUSTOM_RULE_LINK=1
%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
	$(LD) $(LDFLAGS) $(TARGET_STARTFILES) ${filter-out %.a,$^} ${filter %.a,$^} $(TARGET_LIBFILES) -o $@ -lm
